apiVersion: v1
kind: Service
metadata: 
  name: amir-wordpress-mysql
  labels:
    app: amirs-wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
