node() {
	echo "Loading local shared library"
	def repoPath = sh(returnStdout: true, script: 'pwd').trim()
	echo "repo path: $repoPath"
	library identifier: 'SharedLibrary@master',
			  retriever: modernSCM([$class: 'GitSCMSource', remote: "/var/sharedLib"]), 
			  changelog: false
	echo "doing basicStep:"
	basicStep 'input1'
	basicStep 'input2'
	readme()
	execme()
	echo "Done loading the shared library"
}
