apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongodb # connect the pods, so need to contains the app label of the pods to connect to
  ports:
    - protocol: TCP
      port: 27017 # Service prot - The port you are going to use to connect to the service
      targetPort: 27017 # Container port - The port the service is going to talk to, in deployment -> spec.temaplte.spec.containers.port.containerPort
