apiVersion: v1
kind: Service
metadata: 
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer # Accepts external requests by assigning the service external ip address
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30000 # The port where the external ip is going to be open - the port in the browser, range: 30000-32767

