# Secrets must be already in the cluster when referencing it
apiVersion: v1
kind: Secret
metadata:
  name: mymongo-secret
type: Opaque
data:
  mongo-root-username: YW1pcnNoa2VkeQ== # The values here are base64 encoded
  mongo-root-password: cGFzc3dvcmQ=
